language: node_js
node_js:
  - '5.9.1'
sudo: false
cache:
  directories:
    - node_modules
    - app/bower_components
before_script:
  - 'npm i -g bower gulp'
  - 'npm i' # install npm packages
  - 'bower i' # install bower packages
after_script:
  - 'npm run release' # package the UI
